# Generated by Django 5.2 on 2025-05-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bloodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
