# Generated by Django 5.2 on 2025-05-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodevent',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
