# Generated by Django 5.2 on 2025-05-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bloodevent_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
