# Generated by Django 5.2 on 2025-05-22 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donation',
            unique_together={('donor', 'request')},
        ),
        migrations.AddField(
            model_name='donation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.bloodevent'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.bloodrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='donation',
            unique_together={('donor', 'event'), ('donor', 'request')},
        ),
    ]
